# Generated by Django 2.1.7 on 2019-02-18 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('agency_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('broker_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_type', models.CharField(choices=[('SINGLE_FAMILY_HOME', 'Single-family home'), ('CONDO_HOME', 'Condominium home'), ('MOBILE_HOME', 'Mobile home'), ('CONDO', 'Condo'), ('PLEX', 'Plex'), ('LOFT/STUDIO', 'Loft/Studio'), ('LOT', 'Lot'), ('HOBBY FARM', 'Hobby Farm'), ('INTERGENERATIONAL', 'Intergenerational')], default='SINGLE_FAMILY_HOME', max_length=20)),
                ('property_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_for_sale', models.BooleanField(default=True)),
                ('cost', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('num_of_bedrooms', models.IntegerField(default=0)),
                ('num_of_bathrooms', models.IntegerField(default=0)),
                ('num_of_parking_spaces', models.IntegerField(default=0)),
                ('num_of_garages', models.IntegerField(default=0)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_waterfront', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('added_on', models.DateField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Broker')),
            ],
            options={
                'ordering': ['added_on'],
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.Broker'),
        ),
    ]
