# Generated by Django 2.1.7 on 2019-02-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-added_on']},
        ),
        migrations.RemoveField(
            model_name='property',
            name='broker',
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
    ]
