# Generated by Django 2.1.7 on 2019-02-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20190224_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-added_on'], 'verbose_name_plural': 'properties'},
        ),
    ]
